services:
  postgres:
    image: postgres:15
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ai_mail_net

  redis:
    image: redis:7
    restart: always
    expose:
      - "6379"
    networks:
      - ai_mail_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  mailworker:
    build:
      context: .
      dockerfile: MailWorker/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      spamassassin:
        condition: service_started
    env_file:
      - .env
    environment:
      PROD_MODE: true
      DB_HOST: postgres
      DB_LOGIN: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      DB_DATABASE: postgres
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      REDIS_HOST: redis
    networks:
      - ai_mail_net

  backend:
    build:
      context: .
      dockerfile: mail_backend/Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_LOGIN: postgres
      DB_PASSWORD: password
      DB_DATABASE: postgres
      PROD_MODE: true
    ports:
      - "8000:8000"
    networks:
      - ai_mail_net
  
  frontend:
    build:
      context: mail_frontend
      args:
        VITE_BACKEND_URL: http://127.0.0.1:8000
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8001:8001"
    networks:
      - ai_mail_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  aiworker:
    build:
      context: .
      dockerfile: AiWorker/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - ai_mail_net
    environment:
      PROD_MODE: true
      DB_HOST: postgres
      DB_LOGIN: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      DB_DATABASE: postgres

  spamassassin:
    image: axllent/spamassassin
    container_name: spamassassin
    expose:
      - "783"
    restart: unless-stopped
    networks:
      - ai_mail_net

volumes:
  pgdata:

networks:
  ai_mail_net:
    driver: bridge
