@startuml ai_mail_controller
!include ./icons/telegram.puml
!include ./icons/go.puml
!include ./icons/vuejs.puml
!include ./icons/email.puml
!include ./icons/robot.puml

' Участники с иконками
participant Фронтэнд as Vue <<$vuejs>> #3fb984
participant Telegram <<$telegram>> #0088cc
participant Почта <<$email>> #dddddd
participant Бекенд as GoBackend <<$go>> #00acd7
participant Воркер <<$robot>> #dddddd

database DB

Почта -> Worker: СОхраняет новые
Worker -> Почта: Отправляет те что нужно отправить
Worker <-> DB: Сохраняет письмо
DB <-> Воркер: распознаёт письмо
DB -> Telegram: Отправляет уведомление через бота
Vue <- GoBackend: Какие есть письма
Vue -> GoBackend: Выбраное действие с письмом, те как ответить
GoBackend -> DB: Нужно отправить письмо
@enduml