networks:
  fastapi-mail-backend-net:
    driver: bridge

volumes:
  app:
  pgdata:

services:
  postgress-mail:
    image: postgres:15
    container_name: postgress-mail
    restart: always
    expose:
      - "5432"
    environment:
      DB_LOGIN: postgres
      DB_PASSWORD: password
      DB_DATABASE: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fastapi-mail-backend-net

  backend-mail:
    container_name: backend-mail
    build:
      context: ../
      dockerfile: mail_backend/Dockerfile
    depends_on:
      postgress-mail:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"] 
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - DB_HOST=postgress-mail
      - DB_PORT=5432
      - DB_LOGIN=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=postgres
      - PROD_MODE=true
    ports:
      - "8000:8000"
    networks:
      - fastapi-mail-backend-net
