version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mailworker:
    build:
      context: ../
      dockerfile: MailWorker/Dockerfile
    depends_on:
      - redis
    env_file:
      - ../.env
    environment:
      DB_HOST: db
      DB_LOGIN: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      DB_DATABASE: postgres
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}


volumes:
  pgdata:
