name: Build and Push Vue.js Frontend

on:
  push:
    branches: [main]
    paths:
      - 'mail_frontend/**'
      - '.github/workflows/**'
  pull_request:
    branches: [main]
    paths:
      - 'mail_frontend/**'
      - '.github/workflows/**'
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Логин в GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Приведение имени репозитория к нижнему регистру
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: mail_frontend/
          file: mail_frontend/Dockerfile
          build-args: VITE_BACKEND_URL=http://127.0.0.1:8000
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}/mail-frontend
          cache-from: type=gha
          cache-to: type=gha,mode=max